### PR TITLE
ARCH-1378: Updated Confrodo dependencies

### PR DESCRIPTION
**Pull request by MikeTheReader**
[//]: # (VERIFY ALL TESTS AND LINT CHECKS PASS LOCALLY BEFORE PROCEEDING)

[//]: # (can i haz gif plz, kthxbye)
depend

## Description
[//]: # (Replace "PROJECT-ISSUE" in the link below with the ticket number, eg. "ARCH-37")
[JIRA ticket](https://ifitdev.atlassian.net/browse/ARCH-1378)

[//]: # (Describe what changes are made in the pull request. Please add ALL changes that are made and remember to include any minor tweaks that may have snuck in on top of the main objective for the PR.)
Update version of lodash. We were getting security vulnerability messages from Github due to the dependency on an old version. Newer version also moved `merge(a, b, function)` to `mergeWith(a, b, function)`, so updated the test code to reflect that.

## Known Impacted Areas of Code
[//]: # (For the benefit of QA, please list all areas which could possibly be affected by this change. This will help in determining what areas will need to be tested for regression errors. Thoroughness is important here.)
Lodash dependency version -- really all in the testing.

## Steps taken to Recreate / Verify
[//]: # (OPTIONAL - Provide an itemized list of steps needed to recreate the situation that is being addressed by this ticket, or describe in detail what was done to verify that the problem has been resolved or the feature has been completely added.)
Run `yarn install` to get latest lodash version.
Run `yarn mocha` to run tests and confirm they all pass.

### Pull Request Author
I have verified...
- [x] Progressive code cleanup
- [x] Satisfies requirements
- [x] Runs error-free
- [x] Effective commit messages
- [x] User-friendly errors
- [x] Prevent exposing sensitive user information
- [x] Formal documentation
- [x] Test coverage

### Squad Code Reviewer: Steve Griffith
I have verified...
- [x] Satisfies requirements
- [x] Runs error-free
- [x] Effective commit messages
- [x] User-friendly errors
- [x] Prevent exposing sensitive user information
- [x] Formal documentation
- [x] Test coverage

### Chapter Code Reviewer: Joel Detweiler
I have verified...
- [ ] Effective commit messages
- [ ] User-friendly errors
- [ ] Prevent exposing sensitive user information
- [ ] Formal documentation
- [ ] Test coverage

### CODE REVIEW

**Review by loctrice — APPROVED** [review]
image

**Review by jdd1260 — COMMENTED** [review]
Are you positive there aren't more conflicts to expect? I once upgraded from 2 to 3 and broke so many things. I would expect going from 2 to 4 to have even more issues. A big problem was that existing methods were purged or behavior changed

**Comment by MikeTheReader** [comment]
@jdd1260 - This is a small library, and the change I made is literally the only place `lodash` is used.

**Review by jdd1260 — APPROVED** [review]
Thanks for the clarification, @MikeTheReader. I may have been overly worried after I broke so much before

**Pull request merged**
